let arr = [
  {
    id: "64620bde05ab8135825a25ad",
    slug: "shymnagor-jomider-bari",
    title: "শ্যামনগর জমিদার বাড়ি",
    body: "শ্যামপুর জমিদার বাড়ি বাংলাদেশ এর সাতক্ষীরা জেলার শ্যামনগর উপজেলার নকিপুর গ্রামে অবস্থিত এক ঐতিহাসিক জমিদার বাড়ি। যা স্থানীয়দের কাছে রায় চৌধুরীর বাড়ি, জমিদার হরিচরণ রায়ের বাড়ি ও নকিপুর জমিদার বাড়ি নামে পরিচিত।\n\nইতিহাস\nপ্রায় ১৮০০ শতকের মাঝামাঝি সময়ে জমিদার হরিচরণ রায় চৌধুরী এই জমিদার বাড়িটি প্রতিষ্ঠা করেন। তিনি এই এলাকার একজন প্রতাপশালী জমিদার ছিলেন। এই বাড়িতে প্রতিবছর দুর্গা পূজা হতো। যার জন্য বিশেষভাবে একটা পাকা প্যান্ডেল তৈরি করা ছিল। জমিদার হরিচরণ রায় ধনী হওয়ার পেছনে লোকমুখে প্রচলিত রয়েছে তার মা ঘুমের মধ্য স্বপ্নে বস্তা বস্তা টাকা বা গুপ্তধনের সন্ধান পেতেন।(সঠিক কোন প্রমাণ নেই ) আর এই থেকেই হরিচরণ অনেক ধন-সম্পত্তির মালিক হন। তখন থেকে সূর্যাস্ত আইনের মাধ্যমে নিলামে উঠা চৌহার্দিগুলো তিনি কিনে নিতেন। যার ফলস্বরূপ পরবর্তীতে তিনি একজন স্বতন্ত্র জমিদার হয়ে উঠেন।\n\nতিনি ছিলেন একজন ভালো অপরূপভাবশালী জমিদার।\n\nলেখক:- মো: সিয়াম হোসেন।(স্থানীয়)\n\nবাড়ি:- শ্যামনগর,কাশিমাড়ী।",
    images: [
      "shumnagor-jobmider-bari-1684147163073.jpg",
      "à¦¶à§à¦¯à¦¾à¦®à¦¨à¦à¦°_à¦à¦®à¦¿à¦¦à¦¾à¦°_à¦¬à¦¾à¦¡à¦¼à¦¿-1684147163082.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["old-house", "satkhira"],
    category: "House",
    memoryType: "Public",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T10:39:25.396Z",
    updatedAt: "2023-05-15T10:39:25.396Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "64620bdd05ab8135825a25ac",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "64620e0705ab8135825a25af",
    slug: "bongshipur-shahi-jame-mosque",
    title: "Bongshipur Shahi Jame Mosque",
    body: "একই রেখায় পাঁচটি গম্বুজ থাকায় এই মসজিদটিকে বাংলায় মুসলিম স্থাপত্যের সবচেয়ে প্রাচীন স্থাপত্যগুলোর একটি হিসেবে বিবেচনা করা হয়। দূর থেকে মসজিদটিকে যাতে সহজে চেনা যায়, সেজন্য মসজিদ কমিটির উদ্যোগে সুউচ্চ মিনার তৈরি করা হয়েছে। মসজিদের সম্পূর্ণ মেঝে ও দেয়াল টাইলস করা হয়েছে। মসজিদের মূল ভবনের ৫ টি কক্ষে ২টি করে এসি লাগানো হয়েছে। প্রতি শুক্রবার জুম্মার নামাযে হাজার হাজার মুসুল্লি এই মসজিদে নামায আদায় করে। জুম্মার দিনে মুসুল্লিদের মিলন মেলায় পরিণত হয় মসজিদ প্রাঙ্গণ। ধর্মপ্রাণ মুসুল্লিরা এ মসজিদটিকে গায়েবী মসজিদ বলেও মনে করে। বহু দুর-দূরান্ত থেকে দর্শনার্থীরা একনজর দেখার জন্য এ মসজিদে ভিড় জমান।",
    images: [
      "bongshipur-shahi-masjid-01-1684147715262.jpg",
      "bongshipur-shahi-masjid-02-1684147715266.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["mosque", "moghod", "old-mosque"],
    category: "Mosque",
    memoryType: "Private",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T10:48:38.467Z",
    updatedAt: "2023-05-15T10:48:38.467Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "64620e0605ab8135825a25ae",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "64620efa05ab8135825a25b2",
    slug: "kali-mondir-shymnagor-satkhira",
    title: "যশোরেশ্বরী কালী মন্দির",
    body: 'যশোরেশ্বরী কালী মন্দির বাংলাদেশের সাতক্ষীরা জেলার একটি বিখ্যাত মন্দির। এ শক্তিপীঠটি সাতক্ষীরার শ্যামনগর উপজেলার ঈশ্বরীপুর গ্রামে অবস্থিত। যশোরেশ্বরী নামের অর্থ "যশোরের দেবী"।[১] হিন্দু ভক্তদের জন্য এটি একটি পবিত্র তীর্থস্থান।\n\nগুরুত্ব\nসত্য যুগে দক্ষ যজ্ঞের পর সতী মাতা দেহ ত্যাগ করলে মহাদেব সতীর মৃতদেহ কাঁধে নিয়ে বিশ্বব্যাপী প্রলয় নৃত্য শুরু করলে বিষ্ণু দেব সুদর্শন চক্র দ্বারা সতীর মৃতদেহ ছেদন করেন। এতে সতী মাতার দেহখণ্ডসমূহ ভারতীয় উপমহাদেশের বিভিন্ন স্থানে পতিত হয় এবং এ সকল স্থানসমূহ শক্তিপীঠ হিসেবে পরিচিতি পায়।[২]\n\nপুরাণ অনুসারে\nমূল নিবন্ধ: শক্তিপীঠ\nযশোরেশ্বরী কালী মন্দির সনাতন ধর্মালম্বীদের কাছে অতি গুরুত্বপূর্ণ একটি স্থান। সারা পৃথিবীতে সনাতন ধর্মের ৫১ পীঠের একটি যশোরেশ্বরী মন্দির। দেশ-বিদেশের বহু সনাতন ধর্মের অনুসারীরা প্রতি বছর শ্যামনগরের ঈশ্বরীপুর যশোরেশ্বরী কালীমন্দির পরিদর্শনে আসেন ও সেখানে দেবীর সন্তুষ্টির জন্য পূজা অর্চনা দিয়ে থাকেন। সনাতন ধর্মালম্বীদের বাইরেও ঐতিহাসিক গুরুত্ব বিবেচনায় অসংখ্য মানুষ বিভিন্ন সময়ে এ কালী মন্দির দর্শন করেন। সানতন ধর্মালম্বীদের বিশ্বাস, দেহত্যাগের পর দেবী সতীর শরীর যে ৫৩ খণ্ড হয়ে যায় তার পাঁচটি খন্ড বাংলাদেশের বিভিন্ন স্থানে ছড়িয়ে পড়ে। অন্য অংশগুলো ভারত, পাকিস্তান, নেপাল, আফগানিস্তান ও চীনে পড়ে। এর মধ্যে ঈশ্বরীপুর গ্রামে সতীর করকমল বা পাণিপদ্ম পতিত হয়।\n\nশাক্তপীঠ  হিন্দু ধর্ম বিশ্বাস অনুসারে ভারত উপমহাদেশে দেবতা শিবের স্ত্রী সতীর বিভিন্ন দেহাংশ ছড়িয়ে থাকা পবিত্র স্থানসমূহ। বাংলা ভাষায় একে সাধারণত বলা হয় পীঠস্থান বা ‘মহাপীঠ’। ‘পীঠ’ শব্দের অর্থ ‘বেদি’ বা ‘আসন’ যেখানে বিষ্ণুচক্রে খন্ডে খন্ডে কর্তিত হওয়ার পর দেবী সতীর (দেবী দুর্গার আরেক নাম) দেহখন্ড পৃথিবীতে পতিত হয়েছিল। প্রচলিত অভিমত অনুসারে মোট একান্নটি শাক্তপীঠ রয়েছে। এই পীঠগুলির যথার্থ অবস্থান নিয়ে তেমন মতৈক্য নেই। মহাপীঠ নিরূপণ নামে একটি জনপ্রিয় প্রাচীন পান্ডুলিপিতে (১৬৯১-১৭২০) এসব পীঠের নাম উলে­খ করা হয়েছে। এই গ্রন্থে বৃহৎ বঙ্গে এবং এর পরিপার্শ্বের এলাকাগুলিতে অবস্থিত মোট ২৩টি পীঠ শনাক্তীকৃত। এগুলির মধ্যে ১৪টি পশ্চিমবঙ্গে এবং ৭টি বাংলাদেশে।\n\nইতিহাস\n\nসংস্কারের পূর্বে যশোরেশ্বরী কালী মন্দির\nধারনা করা হয় যে, মন্দিরটি আনারি নামের এক ব্রাহ্মণ কর্তৃক নির্মিত হয়। তিনি এই যশোরেশ্বরী শক্তিপীঠের ১০০টি দরজা নির্মাণ করেন। কিন্তু মন্দিরটি কখন নির্মিত হয় তা জানা যায়নি। পরবর্তীকালে লক্ষ্মণ সেন ও প্রতাপাদিত্য কর্তৃক তাদের রাজত্বকালে এটির সংস্কার করা হয়েছিল।কথায় আছে যে মহারাজা প্রতাপাদিত্য়ের সেনাপতি এখানকার জঙ্গল থেকে একটি আলৌকিক আলোর রেখা বের হয়ে মানুষের হাতুর তালুর আকারের একটি পাথরখণ্ডের উপর পড়তে দেখেন। পরবর্তীতে প্রতাপদিত্ত্য কালীর পূজা করতে আরম্ভ করেন এবং এই কালী মন্দিরটি নির্মাণ করেন।যশোরেশ্বরী কালী দর্শনের নাম করে সেনাপতি মান সিংহ প্রতাপাদিত্যের দুর্গের নকশা নিয়ে যান। পরে আক্রমণ করে মোগলরা সেটি জয়লাভও করে। কালীর বিগ্রহের সঙ্গে প্রতাপাদিত্য এবং তার সেনাপতি ও পরামশর্দাতা শঙ্কর চট্টোপাধ্যায়কে বন্দি করেন মান সিংহ।জমিদার বাড়ির মধ্যে অবস্থিত ছিল। তৎকালিন     জমিদার বাবু  মায়ের নামে প্রায় ২০০ বিঘা জমি দান করেছিলেন। কিন্তু আজ প্রভাবশালী ভুমিদস্যুরা জাল দলিল সৃষ্টি করে মায়ের মন্দীরের সব জমি দখল করে ভোগদখল করছে।আজ মায়ের মন্দিরের ইটের দেওয়াল খসে পড়ছে।\n\nশক্তি দেবী ও ভৈরব\nতন্ত্রচূড়ামণিতে বলা হয়েছে—\n\n‘যশোরে পানিপদ্ম দেবতা যশোরেশ্বরী চণ্ডশ্চ ভৈরব যত্র তত্র সিদ্ধ ন সংশয়।’\n\nঅর্থাৎ যশোরে সতীর পাণিপদ্ম বা করকমল পড়েছে। দেবীর নাম যশোরেশ্বরী, ভৈরব হলেন চণ্ড।\n\nএই সতীপীঠে কায়মনোবাক্যে পুজো করলে ভক্তের মনোবাসনা পূর্ণ হয় বলে সর্বসাধারণের বিশ্বাস।\n\nবিগ্রহ\nমন্দির-বেদির ওপর প্রতিষ্ঠিত মাতৃ প্রতিমার শুধু মুখমণ্ডলই দৃষ্টিগোচর হয়। শ্রীযশোরেশ্বরীর কণ্ঠের নিচে তার শ্রীহস্ত ও শ্রীচরণ কিছুই নজরে পড়ে না। মূর্তির অবয়ব পুরোটাই মখমলে আবৃত। মায়ের মাথার ওপর টকটকে লাল রঙের চাঁদোয়া। কণ্ঠে রক্তজবার মালা ও নানা অলংকার। মাথায় সোনার মুকুট। লোলজিহ্বা দেবীর ভীষণা মূর্তি। মালদার জাগ্রত জহুরা কালীমাতার মুখমণ্ডলের সঙ্গে কিছুটা সাদৃশ্য রয়েছে যশোরেশ্বরীর। যশোরেশ্বরী মাতা ভীষণদর্শন হলেও মায়ের শ্রীবদনে কী অপূর্ব দেবীভাব। ভক্তের পরম আশ্রয়ের শেষ কথা যেন তিনিই।\n\nপূজা\nমায়ের পুজোয় সমবেত ভক্তগণ ফুল, ফল ও নানাধরনের মিষ্টি আনেন। মাতৃমূর্তির সামনে সুন্দর করে কাঁসার থালা ও মাটির পাত্রে থরে থরে নৈবেদ্য সাজানো হয়। শ্রীযশোরেশ্বরীর পুজো তন্ত্রমতেও হয়।প্রতিবছর মন্দিরে খুব ধুমধাম করে শ্যামাপুজো হয়। মা ভীষণ জাগ্রত। শ্যামাপুজোয় এই মন্দিরে হাজার হাজার ভক্ত পুজো দেন। মানত করেন। বড় করে হোমযজ্ঞ হয়। মাকে নানা অলংকারে সাজানো হয়। মন্দিরের সামনে তিনদিন মেলা বসে। ছাগবলি হয়। মন্দিরের বারান্দায় হিন্দু ভক্তদের পাশাপাশি মুসলমান ভদ্রমহিলারা ও মাকে ভীষণ মান্যি করে। মানত করতে আসে। মানত পূরণ হলে এক জোড়া পায়রা মন্দিরের বারান্দা থেকে উড়িয়ে দেয়া হয়। ।\n\nনাটমন্দির ও স্থাপত্য\nমূল মন্দির সংলগ্ন স্থানে নাটমন্দির নামে একটি বৃহ মঞ্চমণ্ডপ নির্মাণ করা হয়েছিল যেখান হতে দেবীর মুখমণ্ডল দেখা যায়। এটি লক্ষ্মণ সেন বা মহারাজা প্রতাপাদিত্য কর্তৃক ত্রয়োদশ শতাব্দীতে নির্মাণ করা হয়েছিল। কিন্তু কারা এটি নির্মাণ করেছিল তা জানা যায়নি। ১৯৭১ সালের পর এটি ভেঙে পড়ে। সেই সুদৃশ্য, লম্বা-চওড়া বিরাট নাটমন্দিরের আজ কিছুমাত্র অবশিষ্ট নেই। এখন শুধুমাত্র স্তম্ভগুলি দেখা যায়। দু-একটা স্তম্ভ কয়েকশো বছরের নীরব সাক্ষী হয়ে ইটের পাঁজর বের করে দাঁড়িয়ে আছে কোনওরকমে। একদা মন্দিরের চারদিকে সুউচ্চ প্রাচীর ছিল। মূল মন্দিরটি বাদে আর সবকিছুই আজ কালের গর্ভে বিলীন। মন্দিরের নওবতখানা এখন ভগ্নস্তূপ। শ্রীযশোরেশ্বরী মন্দিরের যত শীঘ্র সম্ভব আমূল সংস্কার প্রয়োজন।\n\nনরেন্দ্র মোদীর মন্দির পরিদর্শন\n২০২১ সালে ২৭ মার্চ ভারতের প্রধানমন্ত্রী নরেন্দ্র মোদি সাতক্ষীরার শ্যামনগর উপজেলার যশোরেশ্বরী কালী মন্দির পরিদর্শন করেছেন । উপজেলার ঈশ্বরীপুরে অবস্থিত ঐতিহাসিক এই মন্দিরে মোদির আগমন ঘিরে সাজানো হয়েছিল শ্যামনগর কে। ইতোমধ্যে মন্দির ও প্রাচীর রঙ করে প্রাচীরের ভাঙা অংশ মেরামত করা হয়েছে। মন্দিরের প্রবেশদ্বারে প্রায় ২০০ বছরের পুরনো বটতলা অংশের গর্ত বন্ধ করে ইট-পাথরের মিশ্রণে দৃষ্টিনন্দন বিস্তৃত চাতাল গড়ে তোলা হয়েছে।[৩]',
    images: [
      "joshoreshari_temple-1684147947762.jpg",
      "à¦¯à¦¶à§à¦°à§à¦¶à§à¦¬à¦°à§_à¦à¦¾à¦²à§_à¦®à¦¨à§à¦¦à¦¿à¦°,_à¦à¦¶à§à¦¬à¦°à§à¦ªà§à¦°,_à¦¶à§à¦¯à¦¾à¦®à¦¨à¦à¦°,_à¦¸à¦¾à¦¤à¦à§à¦·à§à¦°à¦¾,_à¦¬à¦¾à¦à¦²à¦¾à¦¦à§à¦¶à¥¤-1684147947799.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["mondir", "satkhira", "old-temple"],
    category: "Heritage",
    memoryType: "Public",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T10:52:40.366Z",
    updatedAt: "2023-05-15T10:52:40.366Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "64620ef905ab8135825a25b1",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "646210be05ab8135825a25b4",
    slug: "walkway-of-akash-lina-eco-tourism-centre-collapsed-in-satkhira",
    title: "Walkway of Akash Lina Eco-Tourism Centre collapsed in Satkhira",
    body: "Tourists including locals and foreigners use the walkway to revel in the scenic beauty of the tourist spot including the Sundarbans\n\n\nA walkway made out of wood at the Akash Lina Eco-Tourism Centre, located beside the Sundarbans in Shyamnagar upazila in Satkhira collapsed on Tuesday morning.\n\nThe authority says the walkway that was on the estuary of the Chuna and Malancho river, collapsed due to the river erosion. Further, one fishing spot and selfie zone adjacent to the walkway also broke down, incurring heavy loss to them.\n\nTourists including locals and foreigners use the walkway to revel in the scenic beauty of the tourist spot including the Sundarbans, they added. \n\nMd Saiful Islam, caretaker of the tourist spot said the bridge suddenly collapsed around Tuesday morning as strong current intensified river erosion recently.\n\nAfter inspecting the area, Md Kamruzzaman, Upazila Nirbahi Officer(UNO) of Shyamnagar said: ''We informed the Satkhira Deputy Commissioner(DC) about the matter. The Water Development Board(WDB) is dumping sand bags to counter the erosion.\n\nThe Eco-Tourism Centre was built under a government project in 2015 to attract local and foreign tourists.",
    images: [
      "akash-nila2-1684148400702.jpg",
      "akash-nila1-1684148408878.jpg",
      "akash-nila3-1684148408879.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["park", "jungle", "mangrove", "satkhira"],
    category: "Other",
    memoryType: "Private",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T11:00:12.962Z",
    updatedAt: "2023-05-15T11:00:12.962Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "646210bc05ab8135825a25b3",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "646211dd05ab8135825a25b7",
    slug: "sundarbans",
    title: "Sundarbans",
    body: "Sundarbans (pronounced /sʌnˈdɑːrbənz/) is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal. Sundarban Reserve Forest (SRF) of Bangladesh is the largest mangrove forest in the world. It spans the area from the Baleswar River in Bangladesh's division of Khulna to the Hooghly River in India's state of West Bengal. It comprises closed and open mangrove forests, land used for agricultural purpose, mudflats and barren land, and is intersected by multiple tidal streams and channels. Sundarbans is home to the world's largest area of mangrove forests.[3] Four protected areas in the Sundarbans are enlisted as UNESCO World Heritage Sites, viz. Sundarbans West (Bangladesh), Sundarbans South (Bangladesh), Sundarbans East (Bangladesh) and Sundarbans National Park (India).[4]\n\nDespite these protections, the Indian Sundarbans were considered endangered in a 2020 assessment under the IUCN Red List of Ecosystems framework.[5] The Sundarbans mangrove forest covers an area of about 10,000 km2 (3,900 sq mi), of which forests in Bangladesh's Khulna Division extend over 6,517 km2 (2,516 sq mi) and in West Bengal, they extend over 3,483 km2 (1,345 sq mi) across the South 24 Parganas and North 24 Parganas districts.[6] The most abundant tree species are sundri (Heritiera fomes) and gewa (Excoecaria agallocha). The forests provide habitat to 453 fauna wildlife, including 290 bird, 120 fish, 42 mammal, 35 reptile and eight amphibian species.[7] Despite a total ban on all killing or capture of wildlife other than fish and some invertebrates, there is a consistent pattern of depleted biodiversity or loss of species in the 20th century, and the ecological quality of the forest is declining.[8]\n\nDespite preservation commitments from both governments, the Sundarbans are under threat from both natural and human-made causes. In 2007, the landfall of Cyclone Sidr damaged around 40% of the Sundarbans. The forest is also suffering from increased salinity due to rising sea levels due to climate change and reduced freshwater supply. In May 2009 Cyclone Aila devastated the Sundarbans with massive casualties. At least 100,000 people were affected by this cyclone.[9][10] The proposed coal-fired Rampal power station situated 14 km (8.7 mi) north of the Sundarbans at Rampal Upazila of Bagerhat District in Khulna, Bangladesh, is anticipated to further damage this unique mangrove forest according to a 2016 report by UNESCO.[11] Climate change is expected to continue to negatively affect both natural systems and human populations in the region, resulting in further ecosystem degradation and climate migration. Experts examining the region recommend further focus on mangrove restoration and management and advocating for adaptation of human populations, through processes like managed retreat and investments in resilient infrastructure.[12]\n\nEtymology\nThe literal meaning of Sundarbans (Bengali: সুন্দরবন, romanized: Sundôrbôn) is \"beautiful forest\". Alternatively, it was proposed that the name is a corruption of Samudraban, Shomudrobôn (\"Sea Forest\"), or Chandra-bandhe, the name of a tribe.[13] However, the likely origin of the word is Sundari or Sundri, the local name of the mangrove species Heritiera fomes abundant in the area.[14]\n\nHistory\n\nVillage in a clearing of the Sundarbans. Drawing by Frederic Peter Layard after an original sketch of 1839\n\nFarm among paddy fields in the Sundarbans, 2010\nThe history of human settlement in the Sundarbans area can be traced back to Mauryan era (4th-2nd century BCE).[15] A ruin of an abandoned city was found in the Baghmara Forest Block that is attributed to Chand Sadagar, a pre-Mauryan semi-historical figure in Bengali folklore.[16] Archaeological excavation at Kapilmuni, Paikgacha Upazilla, north of the Sundarbans in Bangladesh, revealed ruins of urban settlement dating back to the early middle ages.[17] During the Mughal period, forest tracts were leased out by the local rulers for establishing settlements.[16] In 1757, The British East India Company obtained proprietary rights over Sundarbans from the Mughal Emperor Alamgir II and completed mapping the area in 1764. However, systematic forest management started a century later. The first Forest Management Division to have jurisdiction over the Sundarbans was established in 1869. In 1875 a large portion of the mangrove forests was declared as reserved forests under the Indian Forest Act of 1865 (Act VIII of 1865). The remaining portions of the forests were declared a reserve forest the following year and the forest, which was so far administered by the civil administration district, was placed under the control of the Forest Department. A Forest Division, which is the basic forest management and administration unit, was created in 1879 with the headquarters in Khulna, Bangladesh. The first management plan was written for the period 1893–1898.[18][19]",
    images: [
      "1280px-axishirsche_in_den_sundarbans-1684148696671.jpeg",
      "save_the_sundarbans_20-1684148696675.jpg",
      "sundarban_tiger-1684148696679.jpg",
      "sunderbans_village_1839-1684148696684.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["Sundarbans", "bangladesh", "mangrove-jungle"],
    category: "Jungle",
    memoryType: "Public",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T11:04:58.830Z",
    updatedAt: "2023-05-15T11:04:58.830Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "646211dc05ab8135825a25b6",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "646212d505ab8135825a25ba",
    slug: "coxs-bazar",
    title: "Cox's Bazar",
    body: "Cox's Bazar (/ˌkɒksɪz bəˈzɑː/; Bengali: কক্সবাজার, romanized: Kôksbajar; pronounced [kɔksbadʒaɾ]) is a city, fishing port, tourism centre, and district headquarters in Southeastern Bangladesh. It is located 150 km (93 mi) south of the city of Chittagong. Cox's Bazar is also known by the name Panowa, which translates literally as \"yellow flower.\" Another old name was \"Palongkee\". Kutupalong refugee camp with more than a million Rohingya refugees is in Cox's Baxar.[2][3]\n\nThe city covers an area of 23.4 km2 (9.0 sq mi) with 58 mahallas and 27 wards and as of 2011 had a population of 265,500.27[1] Cox's Bazar is connected by road and air with Chittagong.[4][5]\n\nThe modern Cox's Bazar derives its name from Captain Hiram Cox, an officer of the British East India Company, a Superintendent of Palongkee outpost. To commemorate his role in refugee rehabilitation work, a market was established and named after him. It is one of Bangladesh's main tourist spots. The city has the longest uninterrupted natural beach in the world.[6] Every year more than a million visitors visit the city from around the world.[7] In 2023 Bangladesh evacuated over 50,000 people to safe shelters as cyclone Mocha approached.[8]\n\nHistory\nDuring the early 9th century, the greater Chittagong area, including Cox's Bazar, was under the rule of Arakan kings until its conquest by the Mughals in 1666.[9] When the Mughal Prince Shah Shuja was passing through the hilly terrain of the present-day Cox's Bazar on his way to Arakan, he was attracted to its scenic and captivating beauty. He commanded his forces to camp there. His retinue of one thousand palanquins stopped there for some time. A place named Dulahazara, meaning \"one thousand palanquins,\" still exists in the area. After the Mughals, the place came under the control of the Tipras and the Arakanese, followed by the Portuguese and then the British.\n\nThe name Cox's Bazar originated from the name of a British East India Company officer, Captain Hiram Cox, who was appointed as the Superintendent of Palonki (today's Cox's Bazar) outpost. He succeeded Warren Hastings, who became the Governor of Bengal following the British East India Company Act in 1773. Cox embarked upon the task of rehabilitation and settlement for the Arakanese refugees in the area.[10] He rehabilitated many refugees in the area, but died in 1799 before finishing his work. To commemorate him, a market was established and named after him, called Cox's Bazar. Cox's Bazar was first established in 1854 and became a municipality in 1869.[9]\n\nAfter the Sepoy Mutiny in 1857, the British East India Company was highly criticised on humanitarian grounds, especially for its opium trade monopoly over the Indian Sub-Continent. However, after its dissolution on January 1 1874, the company's assets, including its armed forces, were acquired by the British Crown. After this takeover, Cox's Bazar was declared a district of the Bengal Province under the British Crown.\n\n20th century\n\nCox's Bazar Map from Series U542, US Army Map Service, 1955\nJust after the end of British rule in 1947, Cox's Bazar became part of East Pakistan. Captain Advocate Fazlul Karim, the first post-independence chairman of Cox's Bazar Municipality, established the Tamarisk Forest along the beach. He wanted to attract tourists as well as to protect the beach from tsunamis. He donated much of his father-in-law's and his own lands as sites for constructing a public library and a town hall. Karim was inspired to build Cox's Bazar as a tourist spot after seeing beaches of Bombay and Karachi, and was a resort pioneer in developing Cox's Bazar as a destination. Karim established a maternity hospital, the stadium and the drainage system by procuring grants from the Ford Foundation and Rockefeller Foundation through correspondence. T. H. Matthews, the principal of the Dacca Engineering College (1–49~1954), was a friend who had helped him in these fundraising efforts. Engineer Chandi Charan Das was the government civil engineer who worked on all these projects.\n\nIn 1959 the municipality was turned into a town committee.[9]\n\nIn 1961 the Geological Survey of Pakistan initiated investigation of radioactive minerals like monazite around the Cox's Bazar sea-beach area.[11]\n\nIn 1971, Cox's Bazar wharf was used as a naval port by the Pakistan Navy's gunboats. This and the nearby airstrip of the Pakistan Air Force were the scene of intense shelling by the Indian Navy during the Bangladesh Liberation War. During the war, Pakistani soldiers killed many people in the town, including eminent lawyer Jnanendralal Chowdhury. The killing of two freedom fighters named Farhad and Subhash at Badar Mokam is also recorded in history.[12]\n\nAfter Bangladesh's independence, Cox's Bazar started to receive administrative attention. In 1972 the town committee of Cox's Bazar was once again turned into a municipality. In 1975, The Government of Bangladesh established a pilot plant at Kalatali.[11] In 1984, Cox's Bazar subdivision was promoted to a district, and five years later (in 1989) the Cox's Bazar municipality was elevated to B-grade.[9] In 1994 (jobs) the Marine Fisheries and Technology Station (MFTS) was established at Cox's Bazar. MFTS is a research station of Bangladesh Fisheries Research Institute (BFRI) headquartered in Mymensingh. The station covers a land area of four hectares and contains five laboratories.[13]",
    images: [
      "cox's_bazar_beach_15-1684148942847.jpg",
      "cox's_bazar_sunset-1684148942849.JPG",
    ],
    likes: [],
    saved: [],
    tags: ["coxsbazar", "seabeach"],
    category: "Sea Beach",
    memoryType: "Private",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T11:09:07.446Z",
    updatedAt: "2023-05-15T11:09:07.446Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "646212d505ab8135825a25b9",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "646214d405ab8135825a25c0",
    slug: "cafe-24-park-bhatiari-hathazari-link-road",
    title: "Cafe 24 Park, Bhatiari - Hathazari Link Road",
    body: "Cafe 24 Park is an army-run park in Bhatiari, Chittagong. Cafe 24 Park has located 7 km from Bhatiari to Hathazari and shortly before Chittagong Cantonment. There is a scenic park, a variety of rides, a restaurant serving international quality food items. Cafe 24 Park is a wonderful place to visit and the inside and outside of the park are neat and tidy.\n\nThe equipment used by the army during the training is made for the general public. Visitors will be able to get a good idea using these for a fixed fee. Cafe 24 Park is a complete exception to the rides at traditional children’s parks or amusement parks.",
    images: [
      "1280px-cafe_24_park,_bhatiari_-_hathazari_link_road_(02)-1684149344034.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["park"],
    category: "Hill Truck",
    memoryType: "Public",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T11:17:37.799Z",
    updatedAt: "2023-05-15T11:17:37.799Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "646214d305ab8135825a25bf",
    place: {
      country: "",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "6462159305ab8135825a25c4",
    slug: "university-of-chittagong",
    title: "University of Chittagong",
    body: "The University of Chittagong (also known as Chittagong University or abbreviated as CU Bengali: চট্টগ্রাম বিশ্ববিদ্যালয়) is a public autonomous research university in Hathazari in Chittagong, Bangladesh. Founded in 1966, it is the third oldest university in Bangladesh. Its 1,754 acres (710 ha) campus is the largest among Bangladeshi universities.[3]",
    images: [
      "1280px-world_peace_pagoda_at_university_of_chittagong_(18)-1684149636135.jpg",
      "1280px-a._f._rahman_hall_at_cu_09-1684149645411.jpeg",
      "bangabandhu_hall,_university_of_chittagong-1684149645412.jpg",
      "chittagong_university_library_(04)-1684149645414.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["university", "chittagong"],
    category: "Other",
    memoryType: "Public",
    readTime: null,
    joined: [],
    createdAt: "2023-05-15T11:20:48.558Z",
    updatedAt: "2023-05-15T11:20:48.558Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "6462159205ab8135825a25c3",
    place: {
      country: "",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "646309ca0ab5234e34f5f181",
    slug: "kaptai-lake",
    title: "Kaptai Lake",
    body: "Kaptai Lake is the largest man made lake in Bangladesh.[1] It is located in the Kaptai Upazila under Rangamati District of Chittagong Division. The lake was created as a result of building the Kaptai Dam on the Karnaphuli River, as part of the Karnaphuli Hydro-electric project. Kaptai Lake's average depth is 100 feet (30 m) and maximum depth is 490 feet (150 m).\n\nHistory\nConstruction of the reservoir for the hydro-electric plant began in 1956 by the Government of East Pakistan.[2] As a result, 54,000 acres (220 km2) of farmland in the Rangamati District went underwater and created the lake. The project was finished in 1961.[3] 40% of the total arable land went underwater as a result of the dam construction and 100,000 people were displaced.[3] The palace of the king of the Chakmas was also flooded and is also underwater.[2] The International Engineering Company and Utah International Inc. received the contract for construction of the dam. The dam is 670.8 meters long, and 54.7 meters high.[1]",
    images: [
      "kaptai_lake_01-1684212151195.jpg",
      "1280px-aronnak_holiday_cottage,_rangamati09-1684212166435.jpg",
      "1280px-sunset_in_kaptai_lake-1684212166437.jpg",
      "1280px-wooden_boats,_kaptai_lake_(01)-1684212166439.jpg",
      "hanging_bridge,_kaptai_lake-1684212166444.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["kaptai", "lake"],
    category: "River",
    memoryType: "Public",
    readTime: 0,
    joined: [],
    createdAt: "2023-05-16T04:42:48.918Z",
    updatedAt: "2023-05-16T04:42:48.918Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "646309c90ab5234e34f5f180",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "64636b03a7f172f621fcf825",
    slug: "this-is-test-5",
    title: "This is test title",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    images: ["img1.jpt", "img2.jpg", "img3.jpg"],
    likes: [],
    saved: [],
    tags: ["allah", "rasul", "mohammad"],
    category: "White",
    memoryType: "Private",
    readTime: 0,
    joined: [],
    createdAt: "2023-05-16T11:37:38.972Z",
    updatedAt: "2023-05-16T11:37:38.972Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "64636b02a7f172f621fcf824",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
  {
    id: "646213b005ab8135825a25bd",
    slug: "foys-lake-chittagong",
    title: "Foy's Lake Chittagong",
    body: "Foy's Lake is a man-made lake in Chittagong, Bangladesh. It was created in 1924 by constructing a dam across the stream that came down from the hills in the northern part of Chittagong. The purpose of creating an artificial lake was to provide water to the residents of the railway colony. It was named after Mr. Foy, a Railway engineer, believed to materialize said project. Pahartali was essentially a railway town containing a workshop, yard, and shed. Presently, a carriage workshop, diesel workshop, loco shed, laboratory, stores, electric workshop, and school (established in 1924) are located here. A good number of railway employees reside in the nearby colony.\n\n\nConcord groups gate to Foy's Lake, in the opposite direction of USTC\nThe area belongs to Railway. However, an amusement park, managed by the Concord Group, is located here.[1]",
    images: [
      "foiz_lake._(photo_by_rabiul_islam)_-_panoramio-1684149144750.jpg",
      "1280px-foye's_lake-1684149153753.jpeg",
      "1280px-foy's_lake,_chittagong._-1684149153755.jpg",
      "foyas_lake_chittagong-1684149153758.jpg",
    ],
    likes: [],
    saved: [],
    tags: ["hill-view"],
    category: "Hill Truck",
    memoryType: "Secret",
    readTime: null,
    joined: ["645da107cb879d3f2e84228f"],
    createdAt: "2023-05-15T11:12:37.265Z",
    updatedAt: "2023-05-15T11:12:37.265Z",
    userId: "645da107cb879d3f2e84228f",
    placeId: "646213af05ab8135825a25bc",
    place: {
      country: "Bangladesh",
    },
    user: {
      id: "645da107cb879d3f2e84228f",
      name: "Yousuf Ahamad",
      avatar: null,
      username: "yousuf4you",
    },
  },
];

console.log(arr.length);
